alunos/urls.py
from django.urls import path
from .views import (AlunoCreate, CursoAlunoCreate, HomeAluno, CursoAlunoList, 
    CursoAlunoDelete, CursoAlunoListPorCurso)

app_name = "alunos"

urlpatterns = [
    path('', HomeAluno.as_view(), name='home_aluno'),
    path('create/', AlunoCreate.as_view(), name='create_aluno'),
    path('matricula/', CursoAlunoCreate.as_view(), name='aluno_matricula'),
    path('list-curso-aluno/',CursoAlunoList.as_view(),name='list_curso_aluno'),
    path('list-aluno-curso/<int:pk>/',CursoAlunoListPorCurso.as_view(),name='list_aluno_curso'),
    path('sair-curso/<int:pk>/',CursoAlunoDelete.as_view(),name='sair_curso'),       
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.urls import re_path as url
from django.conf import settings
from django.views.static import serve

from .views import HomeView, Handler404, Handler500


handler404 = Handler404.as_view()
handler500 = Handler500.as_view()


urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('',HomeView.as_view(),name='home'),
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='create_user')),
    path('alunos/',include('alunos.urls', namespace='alunos')),
    path('cursos/',include('curso.urls',namespace='cursos')),
]

templates/cursos_aluno/delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Apagar</h1>
        </div>
        <form action="" method="POST">
            <p>Deseja realmente cancelar a matricula co curso: <strong>{{ object }}</strong>?</p>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger">Excluir</button>
            
            <a href="{% url 'alunos:list_curso_aluno' %}"> 
                <button type="button" class="btn btn-outline-danger">Cancelar</button>
            </a>
        </form>
    </div>
</div>
{% endblock %}

templates/cursos_aluno/list.html
{% extends 'base.html' %}

{% block container %}
{% if user.is_authenticated %}

<table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">Título</th>
        <th scope="col">Carga horária</th>
        {% if user.is_authenticated %}
            <th scope="col">Opções</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
    {% for curso_aluno in object_list %}
      <tr>
        <td>{{curso_aluno.curso.titulo}}</td>
        <td>{{curso_aluno.curso.carga_horaria}}</td>
                
        {% if user.is_authenticated %}
            <td>
                <a href="{% url 'alunos:sair_curso' curso_aluno.id %}" class="text-danger">
                    <button type="button" class="btn btn-danger">Desfazer matricula</button>
                </a>
            </td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
    <br>
    <h3>Você não possui acesso a esta página.</h3>
{% endif %}

{% endblock %}

templates/cursos_aluno/list_aluno_curso.html
{% extends 'base.html' %}

{% block container %}
{% if user.is_authenticated %}
{% if message.tags  %}
  <p class="text-danger">{{messages}}</p>
{% endif %}
<h3>Lista de alunos matriculados no curso.</h3>
<table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">Aluno</th>
        <th scope="col">CPF</th>
        <th scope="col">Data matricula</th>
      </tr>
    </thead>
    <tbody>
    {% for aluno_curso in object_list %}
      <tr>
        <td>{{aluno_curso.aluno}}</td>
        <td>{{aluno_curso.aluno.user}}</td>
        <td>{{aluno_curso.data_matricula}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
    <br>
    <h3>Você não possui acesso a esta página.</h3>
{% endif %}

{% endblock %}