accounts/urls.py
from django.urls import path
from .views import CustomUserCreate, LoginUser, LogoutUser

app_name = "accounts"

urlpatterns = [
    path('create/', CustomUserCreate.as_view(), name='create_user'),
    path('login/', LoginUser.as_view(), name='login_user'),
    path('logout/',LogoutUser.as_view(),name='logout'),
              
]

alunos/urls.py
from django.urls import path
from .views import (AlunoCreate, CursoAlunoCreate, HomeAluno, CursoAlunoList, 
    CursoAlunoDelete, CursoAlunoListPorCurso)

app_name = "alunos"

urlpatterns = [
    path('', HomeAluno.as_view(), name='home_aluno'),
    path('create/', AlunoCreate.as_view(), name='create_aluno'),
    path('matricula/', CursoAlunoCreate.as_view(), name='aluno_matricula'),
    path('list-curso-aluno/',CursoAlunoList.as_view(),name='list_curso_aluno'),
    path('list-aluno-curso/<int:pk>/',CursoAlunoListPorCurso.as_view(),name='list_aluno_curso'),
    path('sair-curso/<int:pk>/',CursoAlunoDelete.as_view(),name='sair_curso'),       
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.urls import re_path as url
from django.conf import settings
from django.views.static import serve

from .views import HomeView, Handler404, Handler500


handler404 = Handler404.as_view()
handler500 = Handler500.as_view()


urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('',HomeView.as_view(),name='home'),
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='create_user')),
    path('alunos/',include('alunos.urls', namespace='alunos')),
    path('cursos/',include('curso.urls',namespace='cursos')),
]

curso/urls.py
from django.urls import path
from .views import ListCursos

app_name = "cursos"

urlpatterns = [
    path('list/', ListCursos.as_view(), name='list_curso'),       
]

templates/base.html
{% load static %}
<html>
    <head>
        <title>Gerenciador de cursos</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'fa/css/all.min.css' %}">
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="/">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            {% if user.is_superuser %}
                                <a class="nav-link" href="{% url 'admin:index' %}">
                                    Administração
                                </a>
                            {% elif  user.is_authenticated %}
                                <a class="nav-link" href="{% url 'alunos:home_aluno' %}">
                                    Área do aluno
                                </a>
                            {% endif %}
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'cursos:list_curso' %}">
                                Cursos
                            </a>
                        </li>
                        
                    </ul>
                </div>
                {% if user.is_authenticated or user.is_superuser%}
                    <a class="nav-link active" aria-current="page" href="{% url 'accounts:logout' %}">
                        <button type="button" class="btn btn-outline-danger">Sair</button>
                    </a>
                {% else %}
                    <a class="nav-link active" aria-current="page" href="{% url 'accounts:login_user' %}">
                        <button type="button" class="btn btn-outline-primary">Entrar</button>
                    </a>
                {% endif %}
            </div>
        </nav>
        <div class="container">
            <div class="row justify-content-center">
              <div class="col-8">
                <hr class="mt-0 mb-4">
                {% block messages %}
                    {% for message in messages %}
                        <div class='alert alert-{{ message.tags}}'>
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endblock messages %}
                 
                {% block container %}

                    <h1>Seja bem vindo!</h1>
                    <div>
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Doloremque quas quo distinctio qui neque temporibus placeat reprehenderit voluptas aliquam quisquam error nobis quidem obcaecati possimus adipisci, sed magnam voluptate excepturi.</p>
                    </div>
                    <h2>Faça o login para acessar o ambiente desejado.</h2>
                    
                    <br>
                    <br>
                    {% if user.is_authenticated or user.is_superuser%}
                        <a class="nav-link active" aria-current="page" href="{% url 'accounts:logout' %}">
                            <button type="button" class="btn btn-outline-danger">Sair</button>
                        </a>
                    {% else %}
                        <a href="{% url 'accounts:create_user' %}">Se não possui cadastro clique aqui e se cadastre como aluno.</a>
                    {% endif %}
                {% endblock %}
            </div>
        </div>
      </div>
    </body>
</html>

templates/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block container %}
<h2>Cadastrados e alterações</h2>
    <form method="POST" class="table" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="form-group">
            {{form|crispy}}
        </div>
        <button type="submit" class="save btn btn-success ">Salvar</button>
    </form>
{% endblock %}