alunos/urls.py
from django.urls import path
from .views import (AlunoCreate, CursoAlunoCreate, HomeAluno, CursoAlunoList, 
    CursoAlunoDelete, CursoAlunoListPorCurso)

app_name = "alunos"

urlpatterns = [
    path('', HomeAluno.as_view(), name='home_aluno'),
    path('create/', AlunoCreate.as_view(), name='create_aluno'),
    path('matricula/', CursoAlunoCreate.as_view(), name='aluno_matricula'),
    path('list-curso-aluno/',CursoAlunoList.as_view(),name='list_curso_aluno'),
    path('list-aluno-curso/<int:pk>/',CursoAlunoListPorCurso.as_view(),name='list_aluno_curso'),
    path('sair-curso/<int:pk>/',CursoAlunoDelete.as_view(),name='sair_curso'),       
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.urls import re_path as url
from django.conf import settings
from django.views.static import serve

from .views import HomeView, Handler404, Handler500


handler404 = Handler404.as_view()
handler500 = Handler500.as_view()


urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('',HomeView.as_view(),name='home'),
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='create_user')),
    path('alunos/',include('alunos.urls', namespace='alunos')),
    path('cursos/',include('curso.urls',namespace='cursos')),
]

curso/urls.py
from django.urls import path
from .views import ListCursos

app_name = "cursos"

urlpatterns = [
    path('list/', ListCursos.as_view(), name='list_curso'),       
]

curso/models.py
from django.db import models
from monitores.models import Monitor

# Create your models here.
class Curso(models.Model):
    titulo = models.CharField(max_length = 255,verbose_name='Título')
    minitores = models.ManyToManyField(Monitor,verbose_name="Monitores")
    carga_horaria = models.IntegerField(verbose_name='Carga horária')
    data = models.DateField()
    numero_vagas = models.IntegerField(verbose_name='Quantidade de vagas')
    prublco_alvo = models.CharField(max_length = 255,verbose_name='Público alvo')
    inicio_matriculas = models.DateTimeField(verbose_name='Início das matrículas')
    fim_matriculas = models.DateTimeField(verbose_name='Encerramento das matrículas')

    def __str__(self):
        return self.titulo

curso/views.py
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView,ListView, DeleteView,View
from django.urls import reverse_lazy
# Create your views here.

from .models import Curso

class ListCursos(ListView):
    
    template_name: str = 'curso/list.html'

    def get_queryset(self):
        queryset = Curso.objects.all()
        return queryset

templates/curso/list.html
{% extends 'base.html' %}

{% block container %}

<h3>Listagem dos cursos da plataforma</h3>

<table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">Título</th>
        <th scope="col">Carga horária</th>
        <th scope="col">Vagas</th>
        <th scope="col">Data</th>
        <th scope="col">Público alvo</th>
        <th scope="col">Periodo de inscrição</th>
        {% if user.is_superuser %}
          <th scope="col">Opções</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
    {% for curso in object_list %}
      <tr>
        <td>{{curso.titulo}}</td>
        <td>{{curso.carga_horaria}}</td>
        <td>{{curso.numero_vagas}}</td>
        <td>{{curso.data|date:"d/m/Y"}}</td>
        <td>{{curso.prublco_alvo}}</td>
        <td>
          De <b>{{curso.inicio_matriculas|date:"d/m/Y"}}</b> 
          até <b>{{curso.fim_matriculas|date:"d/m/Y"}}</b>
        </td>
        {% if user.is_superuser %}
          <td>
            <a href="{% url 'alunos:list_aluno_curso' curso.id %}">
              Listar alunos
            </a>
          </td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}